### ISSUE TITLE
[Bug] 404 flicker on page open

### ISSUE THREAD

**Issue by Xavier-IV** [farhan-helmy/ratemysurau#100]
## Replicating

- Head over to: https://carisurau.com/prayer-room-four-seasons-hotel-ebx
- See 404 page for several second
- Finally able to see the page

_Note: On slower network it'll be more prominent (you can throttle Chrome's network to simulate)_

<img width="200" alt="image" src="https://github.com/farhan-helmy/ratemysurau/assets/14009259/b1001261-f56e-416b-901e-67d149c6cf7f">

## Screenshots

<img width="400" alt="image" src="https://github.com/farhan-helmy/ratemysurau/assets/14009259/1af3b0f8-58ea-4214-b509-879a6da1e25c">

User will see 404 screen first even when surau exists.

<img width="400" alt="image" src="https://github.com/farhan-helmy/ratemysurau/assets/14009259/8f8904b1-5e55-4509-8f00-51662e5b14e2">

After several sec, will flicker into the surau details.

## Correct behaviour

- Surau that exists should not show 404.
- If needed, a loading state is better.

**Comment by farhan-helmy** [comment]
Loading state deployed #99 , cuba try test

**Comment by Xavier-IV** [comment]
Awesome, beautiful ghostloading! Can close this.
