### ISSUE TITLE
HIDE TRPC is returning user email in review

### ISSUE THREAD

**Issue by farhan-helmy** [farhan-helmy/ratemysurau#102]
Security ticket as TRPC is returning user email in the request. It can be seen by public

**Comment by farhan-helmy** [comment]
![image](https://github.com/farhan-helmy/ratemysurau/assets/59960562/a5b7ef6f-c787-4ab5-8876-70e573252815)
Reported by https://twitter.com/idil_iman

**Comment by Xavier-IV** [comment]
Hey, can assign this to me? Got a working one locally. Will PR soon.

Never work with trpc before so kindly guide if anything.
