### ISSUE TITLE
Magic link to approve new surau 

### ISSUE THREAD

**Issue by killallskywalker** [farhan-helmy/ratemysurau#19]
Send email to you to approve directly using magic link after submission . So i can have my surau approve faster :)

**Comment by farhan-helmy** [comment]
menarikkk boleh proceed

**Comment by killallskywalker** [comment]
@farhan-helmy aku tak pernah guna stack ni haha tapi saja nak try . Kalau kau okay , aku nak contribute .

**Comment by farhan-helmy** [comment]
bolehhh tuan @killallskywalker assigned to you

**Comment by killallskywalker** [comment]
Cool @farhan-helmy

**Comment by farhan-helmy** [comment]
dekat AWS Lambda pakai https://github.com/serverless-stack/sst . Kalau nak tengok aku deploy bole call jap kat discord

**Comment by killallskywalker** [comment]
@farhan-helmy dah add kat discord
