### ISSUE TITLE
Cek surau untuk solat jumaat 

### ISSUE THREAD

**Issue by ismi-abbas** [farhan-helmy/ratemysurau#21]
![image](https://github.com/farhan-helmy/ratemysurau/assets/77921975/df915fa2-9b2c-4172-ab50-fb6e232d9249)

Place where the idea is originated from, pretty simple.

**Comment by farhan-helmy** [comment]
nice ni, added to backlog

**Comment by farhan-helmy** [comment]
![image](https://github.com/farhan-helmy/ratemysurau/assets/59960562/159b8d59-25b9-4fb6-b1a7-a24270206666)
letak capsule macam tu (solat jumaat) kaler hijau
