### ISSUE TITLE
Improve searching

### ISSUE THREAD

**Issue by ismi-abbas** [farhan-helmy/ratemysurau#26]
I think searching that invoke trpc each time is bad. Maybe use basic filtering all the surau data based on inputs. Therefore we're less dependent on db.

[trpc useContext](https://trpc.io/docs/client/react/useContext)
[tanStack queryClient](https://tanstack.com/query/v4/docs/react/reference/QueryClient) - trpc useContext() wrapper.

Caching could be another way around. Or useContext() function from trpc. Open for suggestion

**Comment by farhan-helmy** [comment]
We can try and implement this, I like the idea of using built in caching mechanism
