### ISSUE TITLE
Wrong rating percentage calculation

### ISSUE THREAD

**Issue by ikram220999** [farhan-helmy/ratemysurau#45]
for every star receive from feedback, there are wrong calculation for the percentage
example 

1 star have 1 feedback, it will become 100%,
2 start have 1 feedback, it will become 50%,
and so on

**Comment by farhan-helmy** [comment]
can screenshot 1?

**Comment by ikram220999** [comment]
![image](https://github.com/farhan-helmy/ratemysurau/assets/85838927/4de15dcd-b757-4026-8726-3fc40b79a0a7)

![image](https://github.com/farhan-helmy/ratemysurau/assets/85838927/b5e6c655-a92a-4cc0-971e-e3323270b88d)

**Comment by farhan-helmy** [comment]
norted tq @ikram220999

**Comment by mazfreelance** [comment]
i would like to take this issue.

**Comment by farhan-helmy** [comment]
@mazfreelance assigned to u boss

**Comment by farhan-helmy** [comment]
solved #76
