### ISSUE TITLE
Quick Onboarding Setup

### ISSUE THREAD

**Issue by Xavier-IV** [farhan-helmy/ratemysurau#61]
Assalamualaikum,

There's some issue with initial setup for new onboarding developer to get started quickly.

### 1. Google Identity setup is required

```
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
```

Currently this is a blocker for me to spin locally as I need to setup google identity oauth. Is there env that can bypass this setup for developer to contribute faster?

Edit: I've added a guide you can add to your wiki. Just copy paste.
https://github.com/farhan-helmy/ratemysurau/issues/63

### 2. DB Seed has setup errors

Following the Installation setup in Readme, there's issue with db setup. Migration steps are missing.

Will create a PR to support you in this, as I was able to spin up the db successfully. (plus Readme update)

```
$ yarn
$ yarn db:migrate # will create PR to have this script
$ yarn db:seed # will create PR to have this script
```

Unfortunately, even after seed I can't seem to see the record in the homepage. Suggesting a dummy seed data for contributors.

### 3. Secret exposed for local DB

I believe this was intended for local development, but for safety, best to change to Makefile password to `password`.

<img width="402" alt="image" src="https://github.com/farhan-helmy/ratemysurau/assets/14009259/510b1e63-d887-4c5e-854a-9c3a5163cd83">

### 4. Usage of `.env.local`

You might be using this for separating local and remote, but for new onboarding user, I suggest to keep it simple with `.env`.

```
    # there's `.env.local` here
    "db-seed:local": "NODE_ENV=development dotenv -e .env.local -- prisma db seed"
```
Or we can update Readme to include `.env.local` as part of setup.

**Comment by farhan-helmy** [comment]
Waalaikummussalam awesome stuff Zafranudin! Will checkout ur PR
