### ISSUE TITLE
Remove/restyle scrollbar for windows and linux

### ISSUE THREAD

**Issue by ismi-abbas** [farhan-helmy/ratemysurau#66]
![image](https://github.com/farhan-helmy/ratemysurau/assets/77921975/5e3d6532-c586-480f-a35d-af3326d01433)
Found that the last change didn't looks good on windows.

Adding custom css would be good.

This is just cosmetic, overall function is working property.

**Comment by farhan-helmy** [comment]
asal edit gambar? hahhahahaa

**Comment by ismi-abbas** [comment]
> asal edit gambar? hahhahahaa

Alamak kantoi🤣🤣🤣

**Comment by mirza-sync** [comment]
Hi, I would like to work on this issue

**Comment by ismi-abbas** [comment]
> Hi, I would like to work on this issue

There you go!

**Comment by farhan-helmy** [comment]
tq bos @mirza-sync

**Comment by mirza-sync** [comment]
https://github.com/farhan-helmy/ratemysurau/pull/80 Done

**Comment by farhan-helmy** [comment]
done
