### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by asmyio** [farhan-helmy/ratemysurau#7]
I would like to propose that we improve the readme.md based on this https://www.makeareadme.com/ and this https://dev.to/merlos/how-to-write-a-good-readme-bog

**Comment by farhan-helmy** [comment]
Niceee can proceed

**Comment by ezzylan** [comment]
Hello 👋🏻 Is this issue still open? I think I can help improve the readme file 😄

**Comment by farhan-helmy** [comment]
hello sure you can take this @ezzylan anything cam pm me on fb @ paan helmy

**Comment by ezzylan** [comment]
hi @farhan-helmy, I have created a pull request for this issue [here](https://github.com/farhan-helmy/ratemysurau/pull/44)

**Comment by farhan-helmy** [comment]
nicee terima kasih atas kontribusinya @ezzylan merged
