### ISSUE TITLE
Random surau query for main page

### ISSUE THREAD

**Issue by farhan-helmy** [farhan-helmy/ratemysurau#74]
Right now the way Surau appear on the homepage or u wanna call it index.ts page is select latest added surau limit 5

It would be nice is we can implement:
- simple algorithm to query the surau
- do a random query for surau
- query surau based on user location if the user allow location for carisurau app
- this task can be breakdown further based on the goals

**Comment by Ny0ttt** [comment]
Hello. Can I take this? (newbie here but I will do my best ^^)

and may I know if carisurau app already have Getuserlocation?

**Comment by farhan-helmy** [comment]
can brother, takde lagi setakat ni get user location @Ny0ttt

**Comment by farhan-helmy** [comment]
done
