### ISSUE TITLE
Error Page handling

### ISSUE THREAD

**Issue by Xavier-IV** [farhan-helmy/ratemysurau#83]
## Overview

Allow unhandled routes to redirect to 404 pages. Currently it's flickering a surau page, and then stucked at loading.

E.g., head over to:
https://carisurau.com/test-non-existing-url

<img width="400" alt="image" src="https://github.com/farhan-helmy/ratemysurau/assets/14009259/c8d0cd5c-f2b7-439f-9e4d-3cdbadbe3253">

And you'll stuck at "Loading..." page. 404 page would be friendlier.

**Comment by ezzylan** [comment]
Hello, I've created PR #88 for this issue. Feel free to check 😁

**Comment by farhan-helmy** [comment]
tq @ezzylan changes deployed successfully :)
