### ISSUE TITLE
[Feature] Click Esc Key to exit Surau Search

### ISSUE THREAD

**Issue by naimhasim** [farhan-helmy/ratemysurau#85]
### Feature description
When user search for a surau, user can click **Esc** key instead of clicking _Go back_.
<img width="350" alt="image" src="https://github.com/farhan-helmy/ratemysurau/assets/53414003/ae6ec50c-e9f4-4b55-b7f7-b444a776610c">

A small and handy feature that will improve user experience

**Comment by ezzylan** [comment]
Hello, I've created PR #89  for this issue. Feel free to check 😁
