### ISSUE TITLE
Migrate from uploadthing to S3

### ISSUE THREAD

**Issue by farhan-helmy** [farhan-helmy/ratemysurau#95]
## Migrate back from uploadthing to S3

Realll issue, I try to upload pictures during inside MRT just now but it couldn't pass through.
I suspect it is because intermittent connection issue since UploadThing is using US server

**Comment by ADIBzTER** [comment]
How the current implementation works? 

`Client -> Web Server(Singapore?) -> UploadThing (US?)`
or
`Client ->  UploadThing (US?)`

**Comment by farhan-helmy** [comment]
The later

**Comment by farhan-helmy** [comment]
tolong buat dib @ADIBzTER

**Comment by ADIBzTER** [comment]
Too lazy to contribute😔. Can support only

**Comment by natashaamin** [comment]
hiii farhan, would love to learn about infra side. may i know how can i help as a start to solve this problem?

**Comment by farhan-helmy** [comment]
Hello @natashaamin this issue is actually more on the code implementation side, you can take  a look at customuploader component.

Currently it is uploading on uploadthing.com, we wanna change that to upload to S3. I think by tweaking `CustomUploader.tsx`  and creating function / API endpoint to upload to S3 is good enough for start.

LMK and can PM me on discord @ farhan-helmy if you need access to our AWS Account TQ
